### ISSUE TITLE
在服务器上运行时的 Bug (POST /account/login)

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#25]
```
[app.coffee-0 (err) 2014-03-17T12:54:16] ReferenceError: callback is not defined
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/core/model/Account.coffee:94:16
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/core/model/Account.coffee:83:7
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/core/model/Model.coffee:53:9
[app.coffee-0 (err) 2014-03-17T12:54:16]   at args.(anonymous function) (/root/RootPanel/core/model/Model.coffee:13:5)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/node_modules/mongodb/lib/mongodb/collection/query.js:147:5
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Cursor.nextObject (/root/RootPanel/node_modules/mongodb/lib/mongodb/cursor.js:733:5)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at commandHandler (/root/RootPanel/node_modules/mongodb/lib/mongodb/cursor.js:713:14)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/node_modules/mongodb/lib/mongodb/db.js:1806:9
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Server.Base._callHandler (/root/RootPanel/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at /root/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
[app.coffee-0 (err) 2014-03-17T12:54:16]   at [object Object].MongoReply.parseBody (/root/RootPanel/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at [object Object].<anonymous> (/root/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at [object Object].EventEmitter.emit (events.js:95:17)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at [object Object].<anonymous> (/root/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at [object Object].EventEmitter.emit (events.js:98:17)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Socket.<anonymous> (/root/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Socket.EventEmitter.emit (events.js:95:17)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Socket.<anonymous> (_stream_readable.js:746:14)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Socket.EventEmitter.emit (events.js:92:17)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at emitReadable_ (_stream_readable.js:408:10)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at emitReadable (_stream_readable.js:404:5)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at readableAddChunk (_stream_readable.js:165:9)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at Socket.Readable.push (_stream_readable.js:127:10)
[app.coffee-0 (err) 2014-03-17T12:54:16]   at TCP.onread (net.js:528:21)
```

这个是 POST /account/login/ 的时候的。

**Comment by jysperm** [comment]
```
[app.coffee-0 (err) 2014-03-17T12:54:17] Failed to load c++ bson extension, using pure JS version
```

这个是启动程序时的。

**Comment by lyd600lty** [comment]
这个没事
在 2014年3月17日，下午8:55，精英王子 notifications@github.com 写道：

**Comment by jysperm** [comment]
为什么？

**Comment by jysperm** [comment]
没懂
