### ISSUE TITLE
登录之后进入panel报错

### ISSUE THREAD

**Issue by lyd600lty** [HackPlan/RootPanel#47]
```
TypeError: /Users/Yudong/github/RootPanel/core/view/panel.jade:31
    29|           table.table.table-hover
    30|             tbody
  > 31|               for plan in plans
    32|                 tr
    33|                   td= plan.t_name
    34|                   td= plan.t_service

Cannot read property 'length' of undefined
    at jade_debug.unshift.lineno (eval at <anonymous> (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:172:8), <anonymous>:310:31)
    at eval (eval at <anonymous> (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:172:8), <anonymous>:449:4)
    at eval (eval at <anonymous> (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:172:8), <anonymous>:512:21)
    at res (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:173:38)
    at Object.exports.render (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:269:10)
    at Object.exports.renderFile (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:305:18)
    at View.exports.renderFile [as engine] (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:290:21)
    at View.render (/Users/Yudong/github/RootPanel/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/Users/Yudong/github/RootPanel/node_modules/express/lib/application.js:502:10)
    at ServerResponse.res.render (/Users/Yudong/github/RootPanel/node_modules/express/lib/response.js:779:7)
GET /panel/ 500 310ms - 1.43kb
```

**Comment by jysperm** [comment]
这个文件解决了没有？

**Comment by lyd600lty** [comment]
解决
