### ISSUE TITLE
还是bug了。

### ISSUE THREAD

**Issue by lyd600lty** [HackPlan/RootPanel#56]
```
/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;      
              ^
TypeError: Cannot read property 'map' of undefined
  at _map (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:54:16)
  at _asyncMap (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:237:15)
  at Object.map (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:219:23)
  at async.map.widgets (/Users/Yudong/github/RootPanel/core/api/panel.js:42:26)
  at /Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:249:17
  at /Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:46:24)
  at async.each (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:124:9)
  at _asyncMap (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:248:13)
  at Object.map (/Users/Yudong/github/RootPanel/node_modules/async/lib/async.js:219:23)
  at /Users/Yudong/github/RootPanel/core/api/panel.js:39:24
  at Object.exports.checkBilling (/Users/Yudong/github/RootPanel/core/billing.js:13:14)
  at module.exports.get./panel/ (/Users/Yudong/github/RootPanel/core/api/panel.js:26:24)
  at /Users/Yudong/github/RootPanel/core/api/index.js:69:14
  at /Users/Yudong/github/RootPanel/core/api/index.js:59:16
  at /Users/Yudong/github/RootPanel/core/db.js:63:16
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/collection/query.js:159:5
  at Cursor.nextObject (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/cursor.js:742:5)
  at commandHandler (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/cursor.js:716:14)
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/db.js:1846:9
  at Server.Base._callHandler (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
  at [object Object].MongoReply.parseBody (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
  at [object Object].EventEmitter.emit (events.js:95:17)
  at [object Object].<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at Socket.<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)

make: *** [run] Error 8
```

**Comment by jysperm** [comment]
你用那个 ssh 套餐来测试，不要用 all

**Comment by lyd600lty** [comment]
嗯
