### ISSUE TITLE
bug略多。

### ISSUE THREAD

**Issue by lyd600lty** [HackPlan/RootPanel#69]
/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;  
              ^
ReferenceError: last_billing_at is not defined
  at /Users/Yudong/github/RootPanel/core/billing.coffee:59:24
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/collection/core.js:572:7
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/db.js:1132:7
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/db.js:1846:9
  at Server.Base._callHandler (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
  at /Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:478:18
  at [object Object].MongoReply.parseBody (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)
  at [object Object].EventEmitter.emit (events.js:95:17)
  at [object Object].<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at Socket.<anonymous> (/Users/Yudong/github/RootPanel/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:745:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:407:10)
  at emitReadable (_stream_readable.js:403:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)

make: **\* [run] Error 8

**Comment by lyd600lty** [comment]
GET / 302 8.623 ms - 70
TypeError: /Users/Yudong/github/RootPanel/plugin/phpfpm/view/widget.jade:2
    1| header PHP-FPM

> 2| if account.attribute.plugin.phpfpm.is_enable
>     3|   button.btn.btn-danger#php-fpm 关闭
>     4| else
>     5|   button.btn.btn-success#php-fpm 运行

Cannot read property 'phpfpm' of undefined
  at eval (<anonymous>:19:30)
  at eval (<anonymous>:48:21)
  at res (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:173:38)
  at Object.exports.render (/Users/Yudong/github/RootPanel/node_modules/jade/lib/jade.js:269:10)

**Comment by lyd600lty** [comment]
panel，ticket都不能访问的

**Comment by jysperm** [comment]
已修复
